# Generated by Django 5.2.13 on 2026-04-24 05:19

import apps.restaurant.models.menu
import apps.restaurant.models.restaurant
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('category', models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('Beverage', 'beverage'), ('side_dish', 'Side Dish')], db_index=True, default='appetizer', max_length=20)),
                ('dietary_info', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free'), ('none', 'None')], default='none', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/image/', validators=[apps.restaurant.models.menu.validate_image])),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('preparation_time', models.DurationField(help_text='Preparation time')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cuisine_type', models.CharField(choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('mexican', 'Mexican'), ('american', 'American'), ('japanese', 'Japanese'), ('thai', 'Thai'), ('mediterranean', 'Mediterranean')], db_index=True, default='indian', help_text='Type of Cuisine', max_length=30)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logo/', validators=[apps.restaurant.models.restaurant.validate_logo])),
                ('banner', models.ImageField(blank=True, null=True, upload_to='restaurants/banner/', validators=[apps.restaurant.models.restaurant.validate_banner])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
