# Generated by Django 5.2.13 on 2026-05-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_specialhours_operatinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='day_of_week',
            field=models.IntegerField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], db_index=True, default='0'),
        ),
    ]
