# Generated by Django 5.2.13 on 2026-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_operatinghours_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='day_of_week',
            field=models.IntegerField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], db_index=True, default='1'),
        ),
        migrations.AlterUniqueTogether(
            name='specialhours',
            unique_together={('restaurant', 'date')},
        ),
    ]
