# Generated by Django 5.2.13 on 2026-06-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_operatinghours_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, default=0),
        ),
    ]
