# Generated by Django 5.2.13 on 2026-04-24 05:19

import apps.users.models.profile
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('pin_code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Username for login', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='Email address for login and notifications', max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact number for notifications', max_length=20, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('restaurant_owner', 'Restaurant Owner'), ('delivery_driver', 'Delivery Driver')], db_index=True, default='customer', help_text='Type of user', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this user account active?')),
                ('is_verified', models.BooleanField(default=False, help_text='Has the user verified their email?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.users.models.profile.validate_avatar])),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('default_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for', to='users.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.customerprofile'),
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.users.models.profile.validate_avatar])),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car')], db_index=True, default='bike', help_text='Type of Vehicle', max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
