# Generated by Django 5.2.12 on 2026-04-03 08:29

import apps.users.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customerprofile_address_driverprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.users.models.profile.validate_avatar]),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.users.models.profile.validate_avatar]),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car')], db_index=True, default='bike', help_text='Type of Vehicle', max_length=20),
        ),
    ]
