# Generated by Django 5.2.12 on 2026-04-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customerprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant_owner', 'Restaurant Owner'), ('delivery_driver', 'Delivery Driver')], db_index=True, default='customer', help_text='Type of user', max_length=50),
        ),
    ]
