# Generated by Django 5.2.13 on 2026-05-12 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('restaurant', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('delivery', 'Delivery'), ('food', 'Food'), ('packaging', 'Packaging')], max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='contact_preference',
            field=models.CharField(choices=[('call', 'Call'), ('text', 'Text'), ('do_not_disturb', 'Do Not Disturb')], default='call', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contactless_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='utensils_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('full_refund_window', models.IntegerField(default=5)),
                ('partial_refund_window', models.IntegerField(default=15)),
                ('partial_refund_percentage', models.IntegerField(default=50)),
                ('allow_customer_cancellation', models.BooleanField(default=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policy', to='restaurant.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was deleted', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('restaurant_unavailable', 'Restaurant_Unavailable'), ('item_unavailable', 'Item_Unavailable'), ('delivery_issue', 'Delivery_Issue'), ('payment_failed', 'Payment_Failed'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('reason_detail', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('refund_percentage', models.IntegerField(choices=[(0, '0%'), (50, '50%'), (100, '100%')], default=0)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
