# Generated by Django 5.2.13 on 2026-05-15 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_instructiontemplate_order_contact_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_preference',
            field=models.CharField(choices=[('call', 'Call'), ('text', 'Text'), ('do_not_disturb', 'Do Not Disturb')], default='call', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderrating',
            name='delivery_speed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='orderrating',
            name='food_quality',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='orderrating',
            name='packaging_quality',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
