# Generated by Django 5.2.13 on 2026-05-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_contact_preference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructiontemplate',
            options={'ordering': ['-usage_count', '-created_at']},
        ),
    ]
