# Generated by Django 5.2.13 on 2026-05-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_instructiontemplate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercancellation',
            name='cancelled_at',
        ),
    ]
